"""empty message

Revision ID: 23b869f8e101
Revises: 288cd3dc5a8
Create Date: 2021-06-04 19:42:03.611492

"""

# revision identifiers, used by Alembic.
revision = '23b869f8e101'
down_revision = '288cd3dc5a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
